   $.fn.fileinputLocales.en = {
        fileSingle: 'file',
        filePlural: 'files',
        browseLabel: '请选择  &hellip;',
        removeLabel: '删除',
        removeTitle: 'Clear selected files',
        cancelLabel: '取消',
        cancelTitle: 'Abort ongoing upload',
        uploadLabel: '上传',
        uploadTitle: 'Upload selected files',
        msgNo: '否',
        msgNoFilesSelected: '没有选择文件',
        msgCancelled: '已取消',
        msgZoomModalHeading: '详细预览',
        msgFileRequired: '你必须选择一个上传文件',
        msgSizeTooSmall: '"{name}"  文件 (<b>{size} KB</b>)太小    必须大于  <b>{minSize} KB</b>.',
        msgSizeTooLarge: '"{name}"  文件 (<b>{size} KB</b>)太大    必须小于 <b>{maxSize} KB</b>.',
        msgFilesTooLess: '你必须选择至少一个文件上传.',
        msgFilesTooMany: '文件上传过多，文件数必须在<b>{m}</b>以内.',
        msgFileNotFound: '没有找到 "{name}" 文件.',
        msgFileSecured: '安全限制阻止读取文件 "{name}".',
        msgFileNotReadable: '"{name}" 文件不能读取.',
        msgFilePreviewAborted: '预览文件 "{name}".',
        msgFilePreviewError: '读取"{name}"文件时发生错误 .',
        msgInvalidFileName: '"{name}"文件中存在无效或不支持的字符 .',
        msgInvalidFileType: '"{name}"文件类型不支持. 只支持"{types}".',
        msgInvalidFileExtension: '"{name}"文件扩展类型不支持. 只支持"{extensions}".',
        msgFileTypes: {
            'image': 'image',
            'html': 'HTML',
            'text': 'text',
            'video': 'video',
            'audio': 'audio',
            'flash': 'flash',
            'pdf': 'PDF',
            'object': 'object'
        },
        msgUploadAborted: '文件上传被中止',
        msgUploadThreshold: '正在处理...',
        msgUploadBegin: '正在初始化...',
        msgUploadEnd: '结束',
        msgUploadEmpty: '没有可用的有效数据可供上传.',
        msgValidationError: '合法性错误',
        msgLoading: '正在加载第{index}个文件 &hellip;',
        msgProgress: '加载第{index}个文件已完成{ percent }%。',
        msgSelected: '{n} {files}已选择',
        msgFoldersNotAllowed: '只拖放文件！已删除文件夹.',
        msgImageWidthSmall: '"{name}"文件的宽度 在{size} px以上.',
        msgImageHeightSmall: '"{name}"文件的高度在{size} px以上.',
        msgImageWidthLarge: '"{name}"文件的宽度不能超过{size} px.',
        msgImageHeightLarge: '"{name}"文件的宽度不能超过{size} px.',
        msgImageResizeError: '无法获取图像尺寸来调整大小.',
        msgImageResizeException: '调整图像大小时出错.<pre>{errors}</pre>',
        msgAjaxError: '{operation}操作出错。请稍后再试一次!',
        msgAjaxProgressError: '{operation}失败',
        ajaxOperations: {
            deleteThumb: 'file delete',
            uploadThumb: 'file upload',
            uploadBatch: 'batch file upload',
            uploadExtra: 'form data upload'
        },
        dropZoneTitle: '拖放文件到这里 &hellip;',
        dropZoneClickTitle: '<br>(或点击选择文件{files})',
        previewZoomButtonTitles: {
            prev: '查看以前的文件',
            next: '查看下一个文件',
            toggleheader: '切换标头',
            fullscreen: '切换全屏',
            borderless: '切换无边框模式',
            close: '关闭详细的预览'
        }
    };
